In [1]:
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
import matplotlib.pyplot as plt
import numpy as np # linear algebra
import pandas as pd

In [2]:
train_df = pd.read_csv('train.csv')
test_df = pd.read_csv('test.csv')
real_y= pd.read_csv('RealSeoulPredictions.csv')

print(train_df.shape)
print(test_df.shape)

(5760, 15)
(3000, 14)

In [4]:
y_train=train_df['y']
x_train=train_df.drop(['ID','y'],axis=1)
x_valid=test_df.drop('ID',axis=1)
#x_test.isna().sum()
x_train.head()

,Date,Hour,Temperature(�C),Humidity(%),Wind speed (m/s),Visibility (10m),Dew point temperature(�C),Solar Radiation (MJ/m2),Rainfall(mm),Snowfall (cm),Seasons,Holiday,Functioning Day
0,01/12/2017,0,-5.2,37,2.2,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
1,01/12/2017,1,-5.5,38,0.8,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
2,01/12/2017,2,-6.0,39,1.0,2000,-17.7,0.0,0.0,0.0,Winter,No Holiday,Yes
3,01/12/2017,3,-6.2,40,0.9,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
4,01/12/2017,4,-6.0,36,2.3,2000,-18.6,0.0,0.0,0.0,Winter,No Holiday,Yes

In [5]:
#columns converting
import datetime as dt

x_train['Functioning Day']=x_train['Functioning Day'].map(dict(Yes=1, No=0))

Holidays_map = {'Holiday': 1, 'No Holiday': 0}
x_train['Holiday']=x_train['Holiday'].map(Holidays_map)

seasons_map = {'Summer': 0, 'Autumn': 1,'Winter':2,'Spring':3}
x_train['Seasons']=x_train['Seasons'].map(seasons_map)

x_train['Date'] = pd.to_datetime(x_train['Date'])
#pd.to_numeric(test_df['Date'])
x_train['Date']=x_train['Date'].map(dt.datetime.toordinal)

#x_train= (x_train-x_train.mean()) / x_train.std()
x_train

,Date,Hour,Temperature(�C),Humidity(%),Wind speed (m/s),Visibility (10m),Dew point temperature(�C),Solar Radiation (MJ/m2),Rainfall(mm),Snowfall (cm),Seasons,Holiday,Functioning Day
0,736341,0,-5.2,37,2.2,2000,-17.6,0.0,0.0,0.0,2,0,1
1,736341,1,-5.5,38,0.8,2000,-17.6,0.0,0.0,0.0,2,0,1
2,736341,2,-6.0,39,1.0,2000,-17.7,0.0,0.0,0.0,2,0,1
3,736341,3,-6.2,40,0.9,2000,-17.6,0.0,0.0,0.0,2,0,1
4,736341,4,-6.0,36,2.3,2000,-18.6,0.0,0.0,0.0,2,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5755,737018,19,8.7,34,2.2,1857,-6.3,0.0,0.0,0.0,1,0,1
5756,737018,20,8.5,32,2.6,1789,-7.2,0.0,0.0,0.0,1,0,1
5757,737018,21,8.8,37,3.8,1750,-5.1,0.0,0.0,0.0,1,0,1
5758,737018,22,8.9,40,3.4,1810,-3.9,0.0,0.0,0.0,1,0,1
5759,737018,23,9.3,43,3.5,1807,-2.6,0.0,0.0,0.0,1,0,1

In [6]:
x_valid['Functioning Day']=x_valid['Functioning Day'].map(dict(Yes=1, No=0))

Holidays_map = {'Holiday': 1, 'No Holiday': 0}
x_valid['Holiday']=x_valid['Holiday'].map(Holidays_map)

seasons_map = {'Summer': 0, 'Autumn': 1,'Winter':2,'Spring':3}
x_valid['Seasons']=x_valid['Seasons'].map(seasons_map)

x_valid['Date'] = pd.to_datetime(x_valid['Date'])
x_valid['Date']=x_valid['Date'].map(dt.datetime.toordinal)

#x_valid= (x_valid-x_valid.mean()) / x_valid.std()
x_valid

,Date,Hour,Temperature(�C),Humidity(%),Wind speed (m/s),Visibility (10m),Dew point temperature(�C),Solar Radiation (MJ/m2),Rainfall(mm),Snowfall (cm),Seasons,Holiday,Functioning Day
0,736684,0,-1.3,90,2.0,259,-2.7,0.0,0.0,2.2,2,0,1
1,736684,1,-1.8,90,1.6,263,-3.2,0.0,0.0,2.2,2,0,1
2,736684,2,-2.2,88,1.4,348,-3.9,0.0,0.0,2.2,2,0,1
3,736684,3,-2.9,89,1.3,288,-4.4,0.0,0.0,2.2,2,0,1
4,736684,4,-3.6,91,1.2,241,-4.8,0.0,0.0,2.2,2,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,737028,19,4.2,34,2.6,1894,-10.3,0.0,0.0,0.0,1,0,1
2996,737028,20,3.4,37,2.3,2000,-9.9,0.0,0.0,0.0,1,0,1
2997,737028,21,2.6,39,0.3,1968,-9.9,0.0,0.0,0.0,1,0,1
2998,737028,22,2.1,41,1.0,1859,-9.8,0.0,0.0,0.0,1,0,1
2999,737028,23,1.9,43,1.3,1909,-9.3,0.0,0.0,0.0,1,0,1

In [9]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)
scaler.mean_
scaler.transform(x_train)

array([[-3.83601388, -1.66132477, -1.51275498, ...,  0.4472136 ,
        -0.20851441,  0.21166765],
       [-3.83601388, -1.51686175, -1.53796258, ...,  0.4472136 ,
        -0.20851441,  0.21166765],
       [-3.83601388, -1.37239873, -1.57997525, ...,  0.4472136 ,
        -0.20851441,  0.21166765],
       ...,
       [ 1.36228082,  1.37239873, -0.33640037, ..., -0.4472136 ,
        -0.20851441,  0.21166765],
       [ 1.36228082,  1.51686175, -0.32799783, ..., -0.4472136 ,
        -0.20851441,  0.21166765],
       [ 1.36228082,  1.66132477, -0.2943877 , ..., -0.4472136 ,
        -0.20851441,  0.21166765]])

In [10]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_valid)
scaler.mean_
scaler.transform(x_valid)

array([[-1.64072357, -1.66132477, -1.19214975, ...,  0.44652785,
        -0.26148818,  0.12751534],
       [-1.64072357, -1.51686175, -1.23373067, ...,  0.44652785,
        -0.26148818,  0.12751534],
       [-1.64072357, -1.37239873, -1.2669954 , ...,  0.44652785,
        -0.26148818,  0.12751534],
       ...,
       [ 1.63311   ,  1.37239873, -0.86781862, ..., -0.4394401 ,
        -0.26148818,  0.12751534],
       [ 1.63311   ,  1.51686175, -0.90939954, ..., -0.4394401 ,
        -0.26148818,  0.12751534],
       [ 1.63311   ,  1.66132477, -0.9260319 , ..., -0.4394401 ,
        -0.26148818,  0.12751534]])

In [11]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import  GradientBoostingRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor

model_params = {
    'SVR': {
        'model': SVR( epsilon =0.1),
        'params' : {
            'gamma': [0.1 , .001 , 0.3 , 0.0001],
            'C': [1,10,20,50,100],
            'kernel': ['rbf','linear']
        }  
    },
    'random_forest': {
        'model': RandomForestRegressor(criterion = "mse" , max_features="auto"),
        'params' : {
            'n_estimators': [1,5,10,50,100,200,300]
        }
    },
    'GB' : {
        'model': GradientBoostingRegressor(subsample=1.0 , criterion='friedman_mse'),
        'params': {
            'loss' :['ls', 'lad', 'huber', 'quantile'] , 
            'learning_rate':[ 0.1 , 0.3 , 0.01 , 0.001 , 0.03 ] ,
            'n_estimators':[50,100,150,200,250,300,350]
        }
    }
}

In [ ]:
from sklearn.model_selection import GridSearchCV
scores = []

for model_name, mp in model_params.items():
    clf =  GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    clf.fit(x_train, y_train)
    scores.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })
    
df = pd.DataFrame(scores,columns=['model','best_score','best_params'])
df